; generated by Slic3r Prusa Edition 1.39.1-prusa3d on 2018-04-29 at 02:04:03

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.33mm
; first layer extrusion width = 0.42mm

M107
M115 U3.1.0 ; tell printer latest fw version
M201 X9000 Y9000 Z500 E10000 ; sets maximum accelerations, mm/sec^2
M203 X500 Y500 Z12 E120 ; sets maximum feedrates, mm/sec
M204 S1500 T1500 ; sets acceleration (S) and retract acceleration (T)
M205 X10 Y10 Z0.2 E2.5 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M83  ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 E18.0 F1000.0;
G1 X60.0 E9.0  F1000.0 ; intro line
G1 X100.0 E12.5  F1000.0 ; intro line
G92 E0.0
M900 K30; Filament gcode
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
;BEFORE_LAYER_CHANGE
;0.2


G1 E-0.80000 F2100.00000
G1 Z0.600 F7200.000
;AFTER_LAYER_CHANGE
;0.2
G1 X96.383 Y94.948 F7200.000
G1 Z0.200 F7200.000
G1 E0.80000 F2100.00000
M204 S1000
G1 F900
G1 X97.132 Y94.312 E0.03080
G1 X98.028 Y93.909 E0.03080
G1 X98.806 Y93.775 E0.02476
G1 X100.441 Y93.769 E0.05125
G1 X101.221 Y93.858 E0.02461
G1 X101.961 Y94.118 E0.02461
G1 X102.626 Y94.536 E0.02461
G1 X103.183 Y95.096 E0.02476
G1 X103.554 Y95.670 E0.02144
G1 X105.272 Y99.143 E0.12149
G1 X105.580 Y100.248 E0.03597
G1 X105.598 Y101.659 E0.04423
G1 X105.505 Y102.345 E0.02173
G1 X105.309 Y102.933 E0.01942
G1 X104.564 Y104.511 E0.05474
G1 X104.054 Y105.139 E0.02533
G1 X103.353 Y105.694 E0.02804
G1 X102.620 Y106.033 E0.02533
G1 X101.781 Y106.211 E0.02686
G1 X100.655 Y106.228 E0.03531
G1 X100.001 Y106.139 E0.02072
G1 X99.195 Y105.849 E0.02684
G1 X98.552 Y105.457 E0.02360
G1 X95.226 Y102.438 E0.14084
G1 X94.682 Y101.555 E0.03253
G1 X94.420 Y100.551 E0.03253
G1 X94.407 Y98.695 E0.05820
G1 X94.597 Y97.759 E0.02994
G1 X94.947 Y97.036 E0.02519
G1 X96.349 Y94.997 E0.07759
G1 X96.657 Y95.209 F7200.000
G1 F900
G1 X97.343 Y94.625 E0.02823
G1 X98.164 Y94.262 E0.02814
G1 X98.848 Y94.150 E0.02175
G1 X100.440 Y94.146 E0.04993
G1 X101.143 Y94.227 E0.02216
G1 X101.813 Y94.465 E0.02229
G1 X102.412 Y94.848 E0.02229
G1 X102.909 Y95.357 E0.02229
G1 X103.223 Y95.850 E0.01834
G1 X104.929 Y99.298 E0.12062
G1 X105.203 Y100.274 E0.03180
G1 X105.221 Y101.634 E0.04264
G1 X105.140 Y102.249 E0.01943
G1 X104.266 Y104.276 E0.06924
G1 X103.813 Y104.847 E0.02284
G1 X103.176 Y105.360 E0.02565
G1 X102.517 Y105.669 E0.02284
G1 X101.756 Y105.834 E0.02439
G1 X100.689 Y105.852 E0.03346
G1 X100.109 Y105.777 E0.01834
G1 X99.371 Y105.515 E0.02457
G1 X98.791 Y105.166 E0.02120
G1 X95.537 Y102.222 E0.13757
G1 X95.040 Y101.434 E0.02922
G1 X94.797 Y100.530 E0.02936
G1 X94.782 Y98.733 E0.05632
G1 X94.953 Y97.883 E0.02719
G1 X95.267 Y97.236 E0.02257
G1 X96.623 Y95.258 E0.07519
G1 X97.556 Y94.936 F7200.000
G1 F900
G1 X98.299 Y94.616 E0.02536
G1 X98.885 Y94.526 E0.01860
G1 X100.440 Y94.523 E0.04876
G1 X101.070 Y94.597 E0.01988
G1 X101.662 Y94.812 E0.01975
G1 X102.191 Y95.155 E0.01975
G1 X102.630 Y95.612 E0.01988
G1 X104.585 Y99.454 E0.13516
G1 X104.827 Y100.302 E0.02765
G1 X104.845 Y101.607 E0.04093
G1 X104.776 Y102.151 E0.01720
G1 X103.965 Y104.046 E0.06462
G1 X103.563 Y104.563 E0.02052
G1 X102.995 Y105.028 E0.02303
G1 X102.408 Y105.308 E0.02039
G1 X101.729 Y105.458 E0.02180
G1 X100.217 Y105.414 E0.04742
G1 X99.544 Y105.179 E0.02234
G1 X99.028 Y104.871 E0.01886
G1 X95.843 Y101.999 E0.13448
G1 X95.394 Y101.302 E0.02600
G1 X95.173 Y100.498 E0.02612
G1 X95.158 Y98.765 E0.05433
G1 X95.310 Y98.004 E0.02434
G1 X95.588 Y97.434 E0.01988
G1 X96.941 Y95.456 E0.07515
G1 X97.510 Y94.975 E0.02335
G1 X97.752 Y95.262 F7200.000
G1 F900
G1 X98.426 Y94.972 E0.02302
G1 X98.923 Y94.902 E0.01574
G1 X100.440 Y94.901 E0.04755
G1 X100.987 Y94.965 E0.01728
G1 X101.508 Y95.156 E0.01740
G1 X101.968 Y95.460 E0.01728
G1 X102.348 Y95.865 E0.01740
G1 X104.242 Y99.611 E0.13163
G1 X104.451 Y100.332 E0.02355
G1 X104.410 Y102.059 E0.05415
G1 X103.661 Y103.819 E0.05997
G1 X103.313 Y104.280 E0.01811
G1 X102.809 Y104.699 E0.02057
G1 X102.296 Y104.948 E0.01787
G1 X101.698 Y105.082 E0.01922
G1 X100.315 Y105.050 E0.04338
G1 X99.712 Y104.841 E0.01999
G1 X99.260 Y104.575 E0.01645
G1 X96.145 Y101.771 E0.13143
G1 X95.746 Y101.165 E0.02272
G1 X95.549 Y100.468 E0.02272
G1 X95.534 Y98.799 E0.05233
G1 X95.666 Y98.129 E0.02142
G1 X95.908 Y97.633 E0.01728
G1 X97.220 Y95.710 E0.07300
G1 X97.706 Y95.301 E0.01993
G1 F5760
G1 X98.426 Y94.972 E-0.27424
G1 F5760
G1 X98.923 Y94.902 E-0.17382
G1 F5760
G1 X99.824 Y94.901 E-0.31194
G1 E-0.04000 F2100.00000
G1 Z0.800 F7200.000
G1 X99.343 Y98.700 F7200.000
G1 Z0.200 F7200.000
G1 E0.80000 F2100.00000
G1 F900
G1 X99.685 Y98.700 E0.01072
G1 X99.686 Y98.876 E0.00551
G1 X99.849 Y98.880 E0.00511
G1 X99.849 Y99.127 E0.00773
G1 X100.106 Y99.141 E0.00807
G1 X99.779 Y99.137 E0.01025
G1 X99.771 Y98.940 E0.00618
G1 X99.578 Y98.940 E0.00604
G1 X99.569 Y98.732 E0.00653
G1 X99.367 Y98.737 E0.00636
G1 X99.208 Y99.118 F7200.000
G1 F900
G1 X98.316 Y99.140 E0.02798
G1 X98.320 Y99.325 E0.00579
G1 X98.167 Y99.325 E0.00480
G1 X98.163 Y99.529 E0.00640
G1 X98.118 Y99.527 E0.00140
G1 X98.118 Y99.127 E0.01254
G1 X98.304 Y99.127 E0.00583
G1 X98.304 Y98.909 E0.00684
G1 X98.514 Y98.909 E0.00658
G1 X98.514 Y98.723 E0.00583
G1 X98.764 Y98.723 E0.00784
G1 X98.764 Y98.529 E0.00608
G1 X98.966 Y98.529 E0.00633
G1 X98.966 Y98.295 E0.00734
G1 X99.217 Y98.295 E0.00785
G1 X99.217 Y98.113 E0.00571
G1 X99.382 Y98.110 E0.00519
G1 X99.382 Y98.323 E0.00670
G1 X100.056 Y98.323 E0.02115
G1 X100.060 Y98.101 E0.00696
G1 X100.061 Y98.508 E0.01276
G1 X100.226 Y98.512 E0.00516
G1 X100.226 Y98.753 E0.00757
G1 X100.483 Y98.756 E0.00806
G1 X100.483 Y99.029 E0.00855
G1 X100.677 Y99.029 E0.00608
G1 X100.679 Y100.387 E0.04259
G1 X100.867 Y100.387 E0.00591
G1 X100.877 Y100.834 E0.01401
G1 X101.882 Y100.834 E0.03151
G1 X101.882 Y101.324 E0.01536
G1 X101.718 Y101.324 E0.00513
G1 X101.713 Y101.515 E0.00600
G1 X101.433 Y101.515 E0.00877
G1 X101.430 Y101.755 E0.00754
G1 X101.325 Y101.685 E0.00396
G1 X101.071 Y101.654 E0.00802
G1 X100.895 Y101.689 E0.00565
G1 X100.809 Y101.747 E0.00322
G1 X100.809 Y101.658 E0.00279
G1 X100.915 Y101.658 E0.00332
G1 X100.915 Y100.936 E0.02263
G1 X100.260 Y100.936 E0.02055
G1 X100.258 Y99.903 E0.03240
G1 X100.036 Y99.911 E0.00695
G1 X100.036 Y99.714 E0.00618
G1 X99.742 Y99.718 E0.00924
G1 X99.742 Y99.513 E0.00641
G1 X99.418 Y99.509 E0.01015
G1 X99.410 Y99.317 E0.00604
G1 X99.216 Y99.317 E0.00606
G1 X99.210 Y99.178 E0.00436
G1 X99.097 Y98.734 F7200.000
G1 F5760
G1 X98.316 Y99.140 E-0.31017
G1 F5760
G1 X98.320 Y99.325 E-0.06391
G1 F5760
G1 X98.167 Y99.325 E-0.05301
G1 F5760
G1 X98.163 Y99.529 E-0.07074
G1 F5760
G1 X98.118 Y99.527 E-0.01542
G1 F5760
G1 X98.118 Y99.127 E-0.13852
G1 F5760
G1 X98.304 Y99.127 E-0.06435
G1 F5760
G1 X98.304 Y99.000 E-0.04389
G1 E-0.04000 F2100.00000
G1 Z0.800 F7200.000
G1 X100.343 Y99.457 F7200.000
G1 Z0.200 F7200.000
G1 E0.80000 F2100.00000
G1 F900
G1 X100.391 Y99.341 E0.00210
G1 F5760
G1 X100.343 Y99.457 E-0.04380
G1 E-0.75620 F2100.00000
G1 Z0.800 F7200.000
G1 X101.247 Y101.218 F7200.000
G1 Z0.200 F7200.000
G1 E0.80000 F2100.00000
G1 F900
G1 X101.104 Y101.288 E0.00291
G1 X101.247 Y101.218 F7200.000
G1 F900
G1 X101.535 Y101.079 E0.00299
G1 X101.693 Y101.079 E0.00149
M106 S255
;BEFORE_LAYER_CHANGE
;0.5


G1 F5760
G1 X101.535 Y101.079 E-0.05490
G1 F5760
G1 X101.247 Y101.218 E-0.11061
G1 E-0.63449 F2100.00000
G1 Z0.800 F7200.000
;AFTER_LAYER_CHANGE
;0.5
M104 S210 ; set temperature
G1 X99.825 Y99.114 F7200.000
G1 Z0.500 F7200.000
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X99.802 Y99.113 E0.00114
G1 X99.793 Y98.916 E0.00949
G1 X99.601 Y98.916 E0.00927
G1 X99.593 Y98.724 E0.00925
G1 X99.662 Y98.724 E0.00333
G1 X99.663 Y98.899 E0.00843
G1 X99.825 Y98.903 E0.00783
G1 X99.825 Y99.054 E0.00723
M204 S1000
G1 X99.757 Y99.498 F7200.000
M204 S800
G1 F900
G1 X99.432 Y99.494 E0.01560
G1 X99.424 Y99.302 E0.00927
G1 X99.231 Y99.302 E0.00930
G1 X99.222 Y99.102 E0.00959
G1 X98.319 Y99.125 E0.04346
G1 X98.319 Y98.924 E0.00968
G1 X98.529 Y98.924 E0.01010
G1 X98.529 Y98.738 E0.00894
G1 X98.779 Y98.738 E0.01203
G1 X98.779 Y98.544 E0.00932
G1 X98.981 Y98.544 E0.00972
G1 X98.981 Y98.310 E0.01126
G1 X99.232 Y98.310 E0.01204
G1 X99.232 Y98.128 E0.00878
G1 X99.367 Y98.125 E0.00651
G1 X99.367 Y98.338 E0.01026
G1 X100.046 Y98.338 E0.03264
G1 X100.047 Y98.523 E0.00887
G1 X100.211 Y98.527 E0.00792
G1 X100.211 Y98.768 E0.01162
G1 X100.468 Y98.771 E0.01236
G1 X100.468 Y99.044 E0.01312
G1 X100.662 Y99.044 E0.00933
G1 X100.664 Y100.402 E0.06532
G1 X100.852 Y100.402 E0.00908
G1 X100.862 Y100.849 E0.02149
G1 X101.867 Y100.849 E0.04832
G1 X101.867 Y101.309 E0.02211
G1 X101.703 Y101.309 E0.00786
G1 X101.698 Y101.500 E0.00920
G1 X101.418 Y101.500 E0.01347
G1 X101.415 Y101.727 E0.01094
G1 X101.338 Y101.675 E0.00447
G1 X101.114 Y101.630 E0.01102
G1 X100.930 Y101.667 E0.00899
G1 X100.930 Y100.921 E0.03588
G1 X100.275 Y100.921 E0.03152
G1 X100.273 Y99.887 E0.04972
G1 X100.051 Y99.895 E0.01066
G1 X100.051 Y99.699 E0.00946
G1 X99.757 Y99.703 E0.01418
G1 X99.757 Y99.558 E0.00693
M204 S1000
G1 X99.656 Y99.190 F7200.000
G1 F5760
G1 X99.432 Y99.494 E-0.11453
G1 F5760
G1 X99.424 Y99.302 E-0.06674
G1 F5760
G1 X99.231 Y99.302 E-0.06698
G1 F5760
G1 X99.222 Y99.102 E-0.06909
G1 F5760
G1 X98.319 Y99.125 E-0.31295
G1 F5760
G1 X98.319 Y98.924 E-0.06970
G1 F5760
G1 X98.492 Y98.924 E-0.06001
G1 E-0.04000 F2100.00000
G1 Z1.100 F7200.000
G1 X98.304 Y99.310 F7200.000
G1 Z0.500 F7200.000
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X98.152 Y99.310 E0.00733
G1 X98.148 Y99.513 E0.00979
G1 X98.133 Y99.513 E0.00071
G1 X98.133 Y99.142 E0.01783
G1 X98.301 Y99.142 E0.00805
G1 X98.303 Y99.250 E0.00519
M204 S1000
G1 X98.157 Y99.271 F7200.000
G1 F5760
G1 X98.152 Y99.310 E-0.05633
G1 F5760
G1 X98.148 Y99.513 E-0.07050
G1 F5760
G1 X98.133 Y99.513 E-0.00512
G1 F5760
G1 X98.133 Y99.142 E-0.12837
G1 F5760
G1 X98.301 Y99.142 E-0.05801
G1 F5760
G1 X98.303 Y99.250 E-0.03735
G1 E-0.44433 F2100.00000
G1 Z1.100 F7200.000
G1 X100.824 Y101.673 F7200.000
G1 Z0.500 F7200.000
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X100.908 Y101.673 E0.00401
G1 X100.832 Y101.719 E0.00427
M204 S1000
G1 X100.897 Y101.714 F7200.000
G1 X101.174 Y101.446 F7200.000
G1 F900
G1 X101.175 Y101.306 E0.00181
G1 F900
G1 X101.193 Y101.272 E0.00067
G1 F900
G1 X101.210 Y101.237 E0.00084
G1 F900
G1 X101.227 Y101.203 E0.00101
G1 F900
G1 X101.242 Y101.189 E0.00059
G1 F900
G1 X101.256 Y101.174 E0.00067
G1 F900
G1 X101.514 Y101.174 E0.00856
G1 X101.674 Y101.079 F7200.000
G1 F900
G1 X101.516 Y101.079 E0.00146
G1 X101.123 Y101.270 E0.00404
G1 F5760
G1 X101.516 Y101.079 E-0.15128
G1 F5760
G1 X101.674 Y101.079 E-0.05471
G1 E-0.59401 F2100.00000
G1 Z1.100 F7200.000
G1 X100.314 Y99.379 F7200.000
G1 Z0.500 F7200.000
G1 E0.80000 F2100.00000
G1 F900
G1 X100.275 Y99.372 E0.00142
G1 F900
G1 X100.168 Y99.349 E0.00369
G1 F5760
G1 X100.275 Y99.372 E-0.03791
G1 E-0.76209 F2100.00000
G1 Z1.100 F7200.000
G1 X99.282 Y98.788 F7200.000
G1 Z0.500 F7200.000
G1 E0.80000 F2100.00000
G1 F900
G1 X99.228 Y98.806 E0.00170
G1 F900
G1 X99.174 Y98.824 E0.00147
G1 F900
G1 X98.972 Y98.827 E0.00445
G1 X99.282 Y98.788 F7200.000
G1 F900
G1 X99.287 Y98.737 E0.00153
G1 F900
G1 X99.283 Y98.531 E0.00581
G1 F5760;_WIPE
G1 X99.287 Y98.737 E-0.07136
G1 E-0.72864 F2100.00000
G1 Z1.100 F7200.000
M107
; Filament-specific end gcode
G4 ; wait
M107 ; turn off fan
G1 X0 Y200; home X axis
G92 E0.0
G1 E-18.0 F1000.0
M84 ; disable motors
; filament used = 5.6mm (0.0cm3)
; total filament cost = 0.0
; estimated printing time = 25s

; avoid_crossing_perimeters = 0
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\n\n
; between_objects_gcode = 
; bridge_acceleration = 1000
; bridge_fan_speed = 100
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 1000
; deretract_speed = 0
; disable_fan_first_layers = 1
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM107 ; turn off fan\nG1 X0 Y200; home X axis\nG92 E0.0\nG1 E-18.0 F1000.0\nM84 ; disable motors
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #FFFF00
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF3232
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_max_volumetric_speed = 15
; filament_notes = "List of materials tested with standart PLA print settings for MK2:\n\nDas Filament\nEsun PLA\nEUMAKERS PLA\nFiberlogy HD-PLA\nFillamentum PLA\nFloreon3D\nHatchbox PLA\nPlasty Mladeč PLA\nPrimavalue PLA\nProto pasta Matte Fiber\nVerbatim PLA\nVerbatim BVOH"
; filament_soluble = 0
; filament_type = PLA
; first_layer_acceleration = 1000
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_speed = 15
; first_layer_temperature = 215
; gcode_comments = 0
; gcode_flavor = marlin
; infill_acceleration = 2000
; infill_first = 0
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_speed = 100
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_fan_speed = 100
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 800
; post_process = 
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK2\n
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 3
; retract_lift = 0.6
; retract_lift_above = 0
; retract_lift_below = 199
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; single_extruder_multi_material = 0
; skirt_distance = 2
; skirt_height = 1
; skirts = 1
; slowdown_below_layer_time = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}200{else}30{endif}; Filament gcode"
; start_gcode = M115 U3.1.0 ; tell printer latest fw version\nM201 X9000 Y9000 Z500 E10000 ; sets maximum accelerations, mm/sec^2\nM203 X500 Y500 Z12 E120 ; sets maximum feedrates, mm/sec\nM204 S1500 T1500 ; sets acceleration (S) and retract acceleration (T)\nM205 X10 Y10 Z0.2 E2.5 ; sets the jerk limits, mm/sec\nM205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec\nM83  ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Y-3.0 F1000.0 ; go outside print area\nG92 E0.0\nG1 E18.0 F1000.0;\nG1 X60.0 E9.0  F1000.0 ; intro line\nG1 X100.0 E12.5  F1000.0 ; intro line\nG92 E0.0
; temperature = 210
; threads = 4
; toolchange_gcode = 
; travel_speed = 120
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_tower = 0
; wipe_tower_per_color_wipe = 15
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; z_offset = 0
; clip_multipart_objects = 1
; dont_support_bridges = 1
; elefant_foot_compensation = 0
; extrusion_width = 0.45
; first_layer_height = 0.2
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.3
; raft_layers = 0
; seam_position = nearest
; support_material = 0
; support_material_angle = 0
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.15
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_synchronize_layers = 0
; support_material_threshold = 45
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; xy_size_compensation = 0
; bottom_solid_layers = 3
; bridge_angle = 0
; bridge_flow_ratio = 0.95
; bridge_speed = 20
; ensure_vertical_shell_thickness = 1
; external_fill_pattern = rectilinear
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 60
; external_perimeters_first = 0
; extra_perimeters = 0
; fill_angle = 45
; fill_density = 50%
; fill_pattern = grid
; gap_fill_speed = 40
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_overlap = 25%
; infill_speed = 80
; overhangs = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 80
; perimeters = 2
; small_perimeter_speed = 80
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; thin_walls = 0
; top_infill_extrusion_width = 0.33
; top_solid_infill_speed = 80
; top_solid_layers = 3
