export const TaskFields = [
  'id',
  'name',
  'active',
  'file',
  'queue',
  'status',
  'owner',
  'pingAt',
  'lockedAt',
  'startedAt',
  'createdAt',
  'completedAt',
  'archivedAt',
  'duration',
  'progress',
  'restarts',
  'message',
  'payload',
  'webhook',
  'fileURL',
  'taskURL',
]

export const PrinterFields = ['id', 'name', 'queue', 'status', 'active', 'online', 'message', 'pingAt', 'state', 'task']
